    MODULE PRSIZES
        INTEGER, PARAMETER :: ISIZE=SELECTED_INT_KIND(8)
        INTEGER, PARAMETER :: DPSIZE=SELECTED_REAL_KIND(8)
        INTEGER, PARAMETER :: PE=4
        INTEGER, PARAMETER :: MAXRECID=200
        INTEGER, PARAMETER :: PC=3
        INTEGER, PARAMETER :: PCT=1
        INTEGER, PARAMETER :: PIR=6
        INTEGER, PARAMETER :: PD=7
        INTEGER, PARAMETER :: PAL=50
        INTEGER, PARAMETER :: MAXFCN=1000000
        INTEGER, PARAMETER :: MAXIC=90
        INTEGER, PARAMETER :: PG=80
        INTEGER, PARAMETER :: PAST_SIZE=4000
        INTEGER, PARAMETER :: MAXNRDS=30
        INTEGER, PARAMETER :: SD=30
        INTEGER, PARAMETER :: PCMORE=0
        INTEGER, PARAMETER :: PES=2
    END MODULE PRSIZES
